### ISSUE TITLE
No logs are sent when records are filtered out

### ISSUE THREAD

**Issue by chucky2305** [newrelic/newrelic-monolog-logenricher-php#45]
## Description

I have set a log level like so:

```
services:
    NewRelic\Monolog\Enricher\Handler:
        arguments:
            $level: !php/const Monolog\Logger::INFO
```

As soon as this $level will filter one element out of the log records, it will not log anything in NewRelic.
Exception: Only when a log is filtered from the end of the log records, it will still work. 

Reason for that is, that json_encode will act different, if an array does not have a "natural" order of indexes. The problem is is demonstrated here:
https://onlinephp.io/c/14d33

## Steps to Reproduce

```
services:
    NewRelic\Monolog\Enricher\Processor:
        tags:
            - { name: monolog.processor }

    NewRelic\Monolog\Enricher\Handler:
        arguments:
            $level: !php/const Monolog\Logger::INFO

    newrelic_fingers_crossed:
        class: Monolog\Handler\FingersCrossedHandler
        arguments:
            $handler: '@NewRelic\Monolog\Enricher\Handler'
```

```
monolog:
   handlers:
       handler_newrelic_fingers_crossed:
            type: service
            id: newrelic_fingers_crossed
```

## Expected Behaviour

That the logs are sent to NewRelic, even if a record was filtered out.

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

PHP 8.0.12 (cli) (built: Nov 17 2021 19:53:29) ( NTS )

monolog/monolog                       2.3.5              Sends your logs to files, sockets, inboxes, databases and various web services
newrelic/monolog-enricher             2.0.0              Monolog components to enable New Relic Logs
symfony/monolog-bridge                v5.3.7             Provides integration for Monolog with various Symfony components
symfony/monolog-bundle                v3.7.0             Symfony MonologBundle

Linux 1171274930e2 5.19.0-40-generic #41~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 31 16:00:14 UTC 2 x86_64 GNU/Linux
